# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7889ba9a1fe19d59ab67ce4b6c4b42042f3bead9067a056c7ed8200d76bd89e34d8e1fa9ce7abc4d30472476af17d11b7045f517539330b51ccde3a10893ec91

test:
  secret_key_base: 0b39a443e9fbd5653fd2aaaf89be485bffbb06c9aa90c69b4830924a1cec4906e6f04b5b51c2576498f657e2f869ecbbde0648c898699b79d2229a7b9b586399

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
